// <auto-generated />
namespace Repository.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tabela_Permissao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tabela_Permissao));
        
        string IMigrationMetadata.Id
        {
            get { return "201705250222198_Tabela_Permissao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
